name: doai
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake
  - pip
  - pip:
    - pandas>=1.4.1
    - bayesian-optimization>=1.1.0
    - imbalanced-learn>=0.7.0
    - importlib-metadata>=1.7.0
    - jinja2-time>=0.2.0
    - lazy-object-proxy>=1.4.3
    - matplotlib-venn>=0.11.5
    - missingno>=0.4.2
    - psutil>=5.8.0
    - prompt-toolkit>=3.0.5
    - pyls-black>=0.4.6
    - pyls-spyder>=0.3.2
    - python-dateutil>=2.8.1
    - python-jsonrpc-server>=0.4.0
    - python-language-server>=0.36.2
    - python-slugify>=5.0.2
    - pywin32-ctypes>=0.2.0
    - rotation-forest>=0.4
    - scikit-learn>=0.23.2
    - sphinxcontrib-applehelp>=1.0.2
    - sphinxcontrib-devhelp>=1.0.2
    - sphinxcontrib-htmlhelp>=1.0.3
    - sphinxcontrib-jsmath>=1.0.1
    - sphinxcontrib-qthelp>=1.0.3
    - sphinxcontrib-serializinghtml>=1.1.4
    - spyder-kernels>=1.10.2
    - text-unidecode>=1.3
    - three-merge>=0.1.1
    - typed-ast>=1.4.1
    - alabaster>=0.7.12
    - argh>=0.26.2
    - atomicwrites>=1.4.0
    - backcall>=0.2.0
    - brotlipy>=0.7.0
    - decorator>=4.4.2
    - defusedxml>=0.6.0
    - entrypoints>=0.3
    - flake8>=3.8.3
    - future>=0.18.2
    - ipython-genutils>=0.2.0
    - isort>=4.3.21
    - kiwisolver>=1.2.0
    - lazy-object-proxy>=1.4.3
    - olefile>=0.46
    - packaging>=20.4
    - paramiko>=2.7.1
    - parso>=0.7.0
    - pathtools>=0.1.2
    - patsy>=0.5.1
    - pluggy>=0.13.1
    - pycodestyle>=2.6.0
    - pyflakes>=2.2.0
    - Pygments>=2.6.1
    - pyparsing>=2.4.7
    - pyrsistent>=0.16.0
    - python-dateutil>=2.8.1
    - pytz>=2020.1
    - PyYAML>=5.3.1
    - pyzmq>=19.0.1
    - rope>=0.17.0
    - seaborn>=0.10.1
    - six>=1.15.0
    - snowballstemmer>=2.0.0
    - sortedcontainers>=2.2.2
    - testpath>=0.4.4
    - traitlets>=4.3.3
    - ujson
    - vecstack>=0.4.0
    - venn>=0.1.3
    - webencodings>=0.5.1
    - wincertstore>=0.2
    - wrapt>=1.11.2
    - xgboost>=1.2.0
    - sklearn
    - zipp>=3.1.0
    - gseapy
