import os


rule all:
    """final rule"""
    input:
         expand("{outputdir}/trained_models.pkl",outputdir=config['outputdir']),
         expand("{outputdir}/figures",outputdir=config['outputdir'])

rule load:
    """load data"""
    input:
         configfile = expand("{inputdir}/config.yaml",inputdir=config["inputdir"]),
    params:
          outputdir =  expand("{outputdir}",outputdir=config['outputdir']),
    output:
        final_data = expand("{outputdir}/raw.pkl",outputdir=config['outputdir'])
    conda:
         "environment.yaml"
         # expand(os.path.join("workflow","environment.yaml"))
    shell:
        "python load.py -c {input.configfile} -o {params.outputdir} -f {output.final_data}"

rule filter:
    """filter data"""
    input:
         config = expand("{inputdir}/config.yaml",inputdir=config['inputdir']),
         input_pickle = expand("{outputdir}/raw.pkl",outputdir=config['outputdir'])
    params:
          outputdir =  expand("{outputdir}",outputdir=config['outputdir']),
    output:
          final_data = expand("{outputdir}/filtered.pkl",outputdir=config['outputdir'])
    conda:
         "environment.yaml",
    shell:
         "python filter.py -c {input.config} -i {input.input_pickle} -o {params.outputdir} -f {output.final_data}"

rule preprocess:
    """preprocess data"""
    input:
         config = expand("{inputdir}/config.yaml",inputdir=config['inputdir']),
         pickle_filtered  = expand("{outputdir}/filtered.pkl",outputdir=config['outputdir']),
         pickle_raw  = expand("{outputdir}/raw.pkl",outputdir=config['outputdir'])
    params:
          outputdir =  expand("{outputdir}",outputdir=config['outputdir']),
    output:
          final_data = expand("{outputdir}/preprocessed.pkl",outputdir=config['outputdir'])
    conda:
         "environment.yaml",
    shell:
         "python preprocess.py -c {input.config} -r {input.pickle_raw} -i {input.pickle_filtered} -o {params.outputdir} -f {output.final_data}"

rule model:
    """model data"""
    input:
         config = expand("{inputdir}/config.yaml",inputdir=config['inputdir']),
         input_pickle = expand("{outputdir}/preprocessed.pkl",outputdir=config['outputdir'])
    params:
          outputdir =  expand("{outputdir}",outputdir=config['outputdir']),
    output:
          final_data = expand("{outputdir}/trained_models.pkl",outputdir=config['outputdir'])
    conda:
         "environment.yaml",
    shell:
         "python model.py -c {input.config} -i {input.input_pickle} -o {params.outputdir} -f {output.final_data}"

rule modeling_results:
    """modeling_results data"""
    input:
         config = expand("{inputdir}/config.yaml",inputdir=config['inputdir']),
         input_pickle = expand("{outputdir}/trained_models.pkl",outputdir=config['outputdir'])
    params:
          outputdir =  expand("{outputdir}",outputdir=config['outputdir']),
    output:
          outputfile =  directory(expand("{outputdir}/figures",outputdir=config['outputdir'])),
    conda:
         "environment.yaml",
    shell:
         "python modeling_results.py -c {input.config} -i {input.input_pickle} -o {params.outputdir}"